"use client"

/**
 * /demo — Client preview page.
 *
 * Shows the genetic partner (株式会社グリース) the actual rendering of their sample
 * report inside the AXEL karte, plus live AXEL responses generated by the same
 * prompt + OpenAI call production uses.
 *
 * Auth: ?token=… is forwarded to the backend (constant-time compared against
 * DEMO_PREVIEW_TOKEN). Without a valid token nothing renders.
 *
 * Intentionally a single file so the URL can be shared without setting up an account.
 */

import { useEffect, useState } from "react"
import { API_CONFIG } from "@/lib/config/api"
import { Loader2, Dna, Sparkles, ChevronDown, Activity, Brain, RefreshCw, AlertCircle } from "lucide-react"

type ConstitutionCategory = {
  label: string
  totalScore: number | null
  level: "low" | "mid" | "high" | null
  subItems: { label: string; score: number | null; level: "low" | "mid" | "high" | null }[]
}
type NutritionCategory = {
  label: string
  totalScore: number | null
  level: "low" | "mid" | "high" | null
  surveyScore: number | null
  geneScore: number | null
  comment: string | null
  suggestions: string[]
}
type GriiceReport = {
  purpose: string | null
  provider: string | null
  constitution: ConstitutionCategory[]
  nutritionStrategy: NutritionCategory[]
  muscleFiber: { score: number; position: string; label: string } | null
}
type DemoUser = {
  name: string
  position: string
  industry: string
  mbti: string
  disc: string
  enneagram: string
  cognitiveTrend: string
  strengths: string
  businessGoal: string
  values: string
  lifestyle: string
}
type RecentLog = { date: string; state: number; fatigue: number; comment: string }

type DemoKarte = {
  displayName: string
  effectiveMode: "AXEL"
  activeSubscriptionType: "INTEGRATED"
  isDemo: true
  user: DemoUser
  schedule: string
  recentLogs: RecentLog[]
  genetics: { hasData: boolean; report: GriiceReport }
}

type AxelResult = { query: string; reply: string }
type AxelResponse = {
  ok: boolean
  generatedAt: string
  systemPromptPreview: string
  results: AxelResult[]
}

const SCORE_COLOR = (score: number | null) => {
  if (score == null) return "#D1D5DB"
  if (score <= 1) return "#10B981"
  if (score === 2) return "#34D399"
  if (score === 3) return "#F59E0B"
  if (score === 4) return "#FB923C"
  return "#EF4444"
}

function ScoreBar({ score, max = 5 }: { score: number | null; max?: number }) {
  if (score == null) return <div className="h-1.5 w-full rounded-full bg-gray-100" />
  const pct = Math.min(100, Math.max(0, (score / max) * 100))
  return (
    <div className="flex items-center gap-2">
      <span className="inline-flex h-5 min-w-[20px] items-center justify-center rounded-md px-1 text-[10px] font-bold text-white tabular-nums" style={{ background: SCORE_COLOR(score) }}>{score}</span>
      <div className="relative h-1.5 flex-1 overflow-hidden rounded-full bg-gray-100">
        <div className="absolute inset-y-0 left-0 rounded-full" style={{ width: `${pct}%`, background: SCORE_COLOR(score) }} />
      </div>
    </div>
  )
}

function ConstitutionRow({ cat }: { cat: ConstitutionCategory }) {
  const [open, setOpen] = useState(false)
  return (
    <div className="rounded-xl border border-gray-100 bg-white p-3">
      <button type="button" onClick={() => setOpen((v) => !v)} className="flex w-full items-center justify-between gap-3 text-left">
        <div className="min-w-0 flex-1">
          <p className="text-[12.5px] font-semibold text-gray-700">{cat.label}</p>
          <div className="mt-1.5"><ScoreBar score={cat.totalScore} /></div>
        </div>
        <ChevronDown className={`h-3.5 w-3.5 flex-shrink-0 text-gray-400 transition-transform ${open ? "rotate-180" : ""}`} />
      </button>
      {open && cat.subItems.length > 0 && (
        <div className="mt-3 space-y-1.5 border-t border-gray-100 pt-3">
          {cat.subItems.map((s) => (
            <div key={s.label} className="grid grid-cols-[1fr_auto] items-center gap-2">
              <span className="truncate text-[11px] text-gray-500">{s.label}</span>
              <ScoreBar score={s.score} />
            </div>
          ))}
        </div>
      )}
    </div>
  )
}

function NutritionCard({ cat }: { cat: NutritionCategory }) {
  const [showSuggestions, setShowSuggestions] = useState(false)
  return (
    <div className="rounded-xl border border-gray-100 bg-white p-3.5 shadow-sm">
      <div className="flex items-baseline justify-between">
        <p className="text-[13px] font-bold text-gray-800">{cat.label}</p>
        <span className="inline-flex h-6 min-w-[24px] items-center justify-center rounded-md px-1.5 text-[11px] font-bold text-white tabular-nums" style={{ background: SCORE_COLOR(cat.totalScore) }}>{cat.totalScore ?? "—"}</span>
      </div>
      <div className="mt-2.5 grid grid-cols-2 gap-2">
        <div className="rounded-lg bg-gray-50 px-2.5 py-1.5">
          <p className="text-[10px] text-gray-400">生活習慣</p>
          <p className="mt-0.5 text-[13px] font-bold tabular-nums" style={{ color: SCORE_COLOR(cat.surveyScore) }}>{cat.surveyScore ?? "—"}</p>
        </div>
        <div className="rounded-lg bg-gray-50 px-2.5 py-1.5">
          <p className="text-[10px] text-gray-400">体質</p>
          <p className="mt-0.5 text-[13px] font-bold tabular-nums" style={{ color: SCORE_COLOR(cat.geneScore) }}>{cat.geneScore ?? "—"}</p>
        </div>
      </div>
      {cat.comment && <p className="mt-2.5 text-[11.5px] leading-relaxed text-gray-600">{cat.comment}</p>}
      {cat.suggestions.length > 0 && (
        <div className="mt-2">
          <button type="button" onClick={() => setShowSuggestions((v) => !v)} className="flex items-center gap-1 text-[11px] font-semibold text-[#2D5A8E]">
            食事の考え方の一例 {showSuggestions ? "▲" : "▼"}
          </button>
          {showSuggestions && (
            <ol className="mt-1.5 list-decimal space-y-1 pl-4 text-[11.5px] leading-relaxed text-gray-600">
              {cat.suggestions.map((s, i) => <li key={i}>{s}</li>)}
            </ol>
          )}
        </div>
      )}
    </div>
  )
}

function MuscleFiberIndicator({ score, label }: { score: number; label: string }) {
  const pct = Math.min(100, Math.max(0, (score / 5) * 100))
  return (
    <div className="rounded-xl border border-gray-100 bg-white p-4">
      <div className="mb-3 flex items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <Activity className="h-4 w-4 text-[#C9A86A]" />
          <p className="text-xs font-semibold" style={{ color: "#2D5A8E" }}>筋線維組成</p>
        </div>
        <span className="text-[11px] text-gray-500">{label}</span>
      </div>
      <div className="relative h-3 w-full rounded-full bg-gradient-to-r from-gray-200 via-orange-200 to-red-300">
        <div className="absolute -top-1.5 text-base" style={{ left: `calc(${pct}% - 8px)` }}>★</div>
      </div>
      <div className="mt-2 flex justify-between text-[10px] font-semibold text-gray-500">
        <span>速筋</span><span>遅筋</span>
      </div>
    </div>
  )
}

function AxelChatBubble({ result, index }: { result: AxelResult; index: number }) {
  return (
    <div className="rounded-2xl border border-gray-100 bg-white p-4 shadow-sm">
      <div className="flex items-start gap-2">
        <div className="flex h-6 w-6 flex-shrink-0 items-center justify-center rounded-full bg-[#2D5A8E] text-[10px] font-bold text-white">Q</div>
        <p className="flex-1 pt-0.5 text-[13px] leading-relaxed text-gray-700">
          <span className="mr-1 text-[10px] font-bold text-[#C9A86A]">Case {index + 1}</span>
          {result.query}
        </p>
      </div>
      <div className="my-3 ml-3 border-l-2 border-dashed border-gray-200" />
      <div className="flex items-start gap-2">
        <div className="flex h-6 w-6 flex-shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-[#C9A86A] to-[#9B7C3F]">
          <Sparkles className="h-3 w-3 text-white" />
        </div>
        <div className="flex-1 rounded-xl bg-gradient-to-br from-[#FAF7F0] to-[#F4ECD9] p-3">
          <p className="whitespace-pre-wrap text-[12.5px] leading-relaxed text-gray-800">{result.reply}</p>
        </div>
      </div>
    </div>
  )
}

export default function DemoPreviewPage() {
  const [token, setToken] = useState<string | null>(null)
  const [karte, setKarte] = useState<DemoKarte | null>(null)
  const [axel, setAxel] = useState<AxelResponse | null>(null)
  const [loading, setLoading] = useState(false)
  const [axelLoading, setAxelLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [showPrompt, setShowPrompt] = useState(false)
  const [systemPrompt, setSystemPrompt] = useState<string | null>(null)

  useEffect(() => {
    const params = new URLSearchParams(window.location.search)
    const t = params.get("token")
    setToken(t)
  }, [])

  useEffect(() => {
    if (!token) return
    setLoading(true)
    setError(null)
    fetch(`${API_CONFIG.BASE_URL}/demo/karte?token=${encodeURIComponent(token)}`)
      .then(async (r) => {
        if (!r.ok) {
          const j = await r.json().catch(() => ({ error: r.statusText }))
          throw new Error(j.error || `HTTP ${r.status}`)
        }
        return r.json()
      })
      .then((j: DemoKarte) => setKarte(j))
      .catch((e) => setError(e.message))
      .finally(() => setLoading(false))
  }, [token])

  const runAxel = async () => {
    if (!token) return
    setAxelLoading(true)
    setError(null)
    try {
      const r = await fetch(`${API_CONFIG.BASE_URL}/demo/axel?token=${encodeURIComponent(token)}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({}),
      })
      if (!r.ok) {
        const j = await r.json().catch(() => ({ error: r.statusText }))
        throw new Error(j.error || `HTTP ${r.status}`)
      }
      const j = (await r.json()) as AxelResponse
      setAxel(j)
    } catch (e: any) {
      setError(e?.message || "応答の生成に失敗しました。もう一度お試しください。")
    } finally {
      setAxelLoading(false)
    }
  }

  const loadSystemPrompt = async () => {
    if (!token || systemPrompt) return
    try {
      const r = await fetch(`${API_CONFIG.BASE_URL}/demo/system-prompt?token=${encodeURIComponent(token)}`)
      if (!r.ok) throw new Error(`HTTP ${r.status}`)
      setSystemPrompt(await r.text())
    } catch (e: any) {
      setError(e?.message || "システムプロンプトの読み込みに失敗しました")
    }
  }

  if (!token) {
    return (
      <div className="mx-auto flex min-h-screen max-w-md flex-col items-center justify-center bg-[#FAFAF7] px-6 text-center">
        <AlertCircle className="mb-3 h-8 w-8 text-amber-500" />
        <p className="text-sm font-semibold text-gray-700">プレビュー トークンが必要です</p>
        <p className="mt-1 text-xs text-gray-500">URL末尾に <code className="rounded bg-gray-100 px-1.5 py-0.5">?token=…</code> を付与してください。</p>
      </div>
    )
  }

  if (loading) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-[#FAFAF7]">
        <Loader2 className="h-6 w-6 animate-spin text-[#C9A86A]" />
      </div>
    )
  }

  if (error && !karte) {
    return (
      <div className="mx-auto flex min-h-screen max-w-md flex-col items-center justify-center bg-[#FAFAF7] px-6 text-center">
        <AlertCircle className="mb-3 h-8 w-8 text-red-500" />
        <p className="text-sm font-semibold text-gray-700">読み込みに失敗しました</p>
        <p className="mt-1 text-xs text-gray-500">{error}</p>
      </div>
    )
  }

  if (!karte) return null

  const { user, schedule, recentLogs, genetics } = karte
  const report = genetics.report

  return (
    <div className="min-h-screen bg-[#FAFAF7]">
      {/* Header */}
      <div className="bg-gradient-to-br from-[#1A2238] via-[#2D5A8E] to-[#1A2238] px-5 py-7 text-white">
        <div className="mx-auto max-w-2xl">
          <div className="flex items-center gap-2">
            <span className="rounded-full bg-[#C9A86A]/30 px-2 py-0.5 text-[10px] font-bold tracking-widest text-[#F4DCA8]">DEMO PREVIEW</span>
            <span className="text-[10px] text-white/60">株式会社グリース 様 共有用</span>
          </div>
          <h1 className="mt-3 text-2xl font-bold tracking-wide" style={{ fontFamily: "serif" }}>AXEL</h1>
          <p className="mt-1 text-xs text-white/70">判断力と健康を統合的に支える AI コンシェルジュ</p>
          <div className="mt-4 rounded-xl border border-white/15 bg-white/5 p-3 text-[11px] leading-relaxed text-white/85">
            このページは、貴社サンプルデータ（Test Data）が AXEL に取り込まれた際、利用者画面（カルテ）と AI 応答に
            どう反映されるかを示すデモです。本ページに表示される利用者「{user.name}」は架空のデモユーザーです。
            AI応答は実運用と同じ system prompt・同じ OpenAI モデル（gpt-4o-mini）でその場で生成されます。
          </div>
        </div>
      </div>

      <div className="mx-auto max-w-2xl space-y-6 px-4 py-6">
        {/* Demo user summary */}
        <section className="rounded-2xl border border-gray-100 bg-white p-4 shadow-sm">
          <h2 className="flex items-center gap-2 text-[12px] font-bold tracking-wider text-[#2D5A8E]">
            <Brain className="h-3.5 w-3.5" /> デモユーザー プロフィール（架空）
          </h2>
          <div className="mt-3 grid grid-cols-2 gap-2 text-[11px]">
            <div><span className="text-gray-400">氏名：</span><span className="font-semibold text-gray-700">{user.name}</span></div>
            <div><span className="text-gray-400">役職：</span><span className="font-semibold text-gray-700">{user.position}</span></div>
            <div><span className="text-gray-400">MBTI：</span><span className="font-semibold text-gray-700">{user.mbti}</span></div>
            <div><span className="text-gray-400">DISC：</span><span className="font-semibold text-gray-700">{user.disc}</span></div>
            <div className="col-span-2"><span className="text-gray-400">事業目標：</span><span className="text-gray-700">{user.businessGoal}</span></div>
          </div>
          <div className="mt-3 rounded-lg bg-gray-50 p-2.5 text-[10.5px] leading-relaxed text-gray-600">
            <span className="font-semibold text-gray-700">本日：</span>{schedule}
          </div>
          <div className="mt-2 grid grid-cols-3 gap-1.5 text-[10px]">
            {recentLogs.map((l) => (
              <div key={l.date} className="rounded-lg border border-gray-100 p-2">
                <p className="text-[9px] text-gray-400">{l.date}</p>
                <p className="text-gray-700">state {l.state} / fatigue {l.fatigue}</p>
                <p className="mt-0.5 truncate text-gray-500">{l.comment}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Karte — Griice report rendered exactly as the LIFF page renders it */}
        {report && (
          <>
            {report.purpose && (
              <section className="rounded-2xl border border-gray-100 bg-white p-4 shadow-sm">
                <h2 className="flex items-center gap-2 text-[12px] font-bold tracking-wider text-[#2D5A8E]">
                  <Dna className="h-3.5 w-3.5" /> 遺伝子分析の目的 <span className="text-[10px] font-normal text-gray-400">／ 出典：{report.provider}</span>
                </h2>
                <p className="mt-2 text-[12px] text-gray-700">{report.purpose}</p>
              </section>
            )}

            {report.nutritionStrategy.length > 0 && (
              <section>
                <h2 className="mb-2 flex items-center gap-2 px-1 text-[12px] font-bold tracking-wider text-[#2D5A8E]">
                  <Sparkles className="h-3.5 w-3.5 text-[#C9A86A]" /> 栄養戦略 6カテゴリ
                </h2>
                <div className="space-y-2.5">
                  {report.nutritionStrategy.map((n) => <NutritionCard key={n.label} cat={n} />)}
                </div>
              </section>
            )}

            {report.constitution.length > 0 && (
              <section>
                <h2 className="mb-2 flex items-center gap-2 px-1 text-[12px] font-bold tracking-wider text-[#2D5A8E]">
                  <Dna className="h-3.5 w-3.5 text-[#C9A86A]" /> 体質傾向 11カテゴリ
                </h2>
                <div className="space-y-2">
                  {report.constitution.map((c) => <ConstitutionRow key={c.label} cat={c} />)}
                </div>
              </section>
            )}

            {report.muscleFiber && (
              <section>
                <MuscleFiberIndicator score={report.muscleFiber.score} label={report.muscleFiber.label} />
              </section>
            )}
          </>
        )}

        {/* AXEL live response demo */}
        <section className="rounded-2xl border-2 border-[#C9A86A]/30 bg-gradient-to-br from-[#FAF7F0] to-white p-5">
          <h2 className="flex items-center gap-2 text-[12px] font-bold tracking-wider text-[#2D5A8E]">
            <Sparkles className="h-3.5 w-3.5 text-[#C9A86A]" /> AXEL ライブ応答デモ
          </h2>
          <p className="mt-1 text-[11px] leading-relaxed text-gray-600">
            上記サンプルデータ + デモユーザープロフィール + 直近ログを、本番と同一の system prompt として
            OpenAI に渡し、リアルタイムで応答を生成します。生成毎に微妙に変わります（temperature=0.25）。
          </p>
          <button
            type="button"
            onClick={runAxel}
            disabled={axelLoading}
            className="mt-3 inline-flex items-center gap-2 rounded-full bg-[#2D5A8E] px-4 py-2 text-[11px] font-bold text-white shadow-sm transition disabled:opacity-50"
          >
            {axelLoading ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <RefreshCw className="h-3.5 w-3.5" />}
            {axel ? "応答を再生成" : "3つの質問で AXEL を試す"}
          </button>

          {axel && (
            <div className="mt-4 space-y-3">
              {axel.results.map((r, i) => <AxelChatBubble key={i} result={r} index={i} />)}
              <p className="text-right text-[9px] text-gray-400">生成時刻：{new Date(axel.generatedAt).toLocaleString("ja-JP")}</p>
            </div>
          )}

          {/* System prompt auditor (optional) */}
          <div className="mt-5 border-t border-gray-200 pt-4">
            <button
              type="button"
              onClick={() => {
                setShowPrompt((v) => !v)
                if (!systemPrompt) loadSystemPrompt()
              }}
              className="text-[10.5px] text-gray-500 underline"
            >
              {showPrompt ? "▲ system prompt を隠す" : "▼ AI に渡している system prompt を確認する"}
            </button>
            {showPrompt && (
              <pre className="mt-2 max-h-80 overflow-y-auto whitespace-pre-wrap rounded-lg bg-gray-900 p-3 text-[10px] leading-relaxed text-gray-200">
{systemPrompt || "loading..."}
              </pre>
            )}
          </div>
        </section>

        <p className="px-2 text-center text-[10px] text-gray-400">
          本デモは株式会社グリース様共有用です。表示中の利用者「{user.name}」は架空のデモユーザーであり、本番DBには存在しません。
        </p>
      </div>
    </div>
  )
}
